---
- hosts: web
  become: yes
  tasks:
    - name: Instalar paquete de Apache
      yum:
        name: 
          - httpd
          - php
        state: present
    - name: Iniciar servicio Apache
      systemd:
        name: httpd
        state: started
        enabled: yes
    - name: Detener firewall de Linux
      systemd:
        name: firewalld
        state: stopped
        enabled: no